-- Lista somente-leitura dos globais do FS25 usados pelos adapters e por main.lua.
-- Cresce conforme novos adapters usarem novas APIs do jogo (F5+).
return {
    "g_storeManager",
    "g_shopController",
    "g_shopMenu",
    "g_modManager",
    "g_brandManager",
    "g_i18n",
    "g_inputBinding",
    "g_gui",
    "g_dedicatedServer",
    "g_currentModDirectory",
    "g_currentModName",
    "g_modSettingsDirectory",
    "g_languageShort",
    "g_modIsLoaded",
    "g_currentMission",
    "ShopMenu",
    "TabbedMenuWithDetails",
    "TextInputDialog",
    "Utils",
    "XMLFile",
    "StoreSpecies",
    "InputAction",
    "addModEventListener",
    "addConsoleCommand",
    "removeConsoleCommand",
    "source",
    "getTimeSec",
    "Logging",
    "createFolder",
}
